name: Financial SOC Threat Detection Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  financial-threat-detection:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v4

    - name: Simular modificaciÃ³n no autorizada en sistema financiero
      run: |
        echo "ALTER TABLE cuentas SET saldo = saldo + 100000;" > financial_change.sql

    - name: Simular acceso administrativo sospechoso
      run: |
        logger "FINANCIAL-SOC: acceso administrativo no autorizado detectado"

    - name: Simular indicador de malware
      run: |
        echo "EICAR-STANDARD-ANTIVIRUS-TEST-FILE" > malware_test.txt
